import os
import time
print("...."*80)
print("hello....WELCOME TO 'KUBERNESTES WORLD'...by SANDEEP KUMAR Patel..")
print("...."*80)
print(" ..Minikube to launch.... ")
print("#"*150)
time.sleep(1)
os.system('minikube start')
print("#"*150)
print("...."*80)
print("NEXT ..Show the minikube status.... ")
print("...."*80)
print("#"*150)
time.sleep(1)
os.system('minikube status')
print("#"*150)
print("...."*80)
print("NEXT ..Show the minikube local ip.... ")
print("...."*150)
time.sleep(1)
print("#"*150)
os.system('minikube ip')
print("#"*150)
print("...."*80)
print("NEXT ..Show pods.... ")
print("...."*150)
time.sleep(1)
print("#"*150)
os.system('kubectl get pods')
print("#"*150)
print("...."*80)
print("NEXT ..Show DASHBOARD.... ")
print("...."*150)
time.sleep(5)
print("#"*150)
os.system('minikube dashboard')


